name: webvalley
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.5.2
  - numpy=1.23.1
  - pandas=1.4.3
  - python=3.9.13
  - pytorch=1.12.0
  - scikit-learn=1.1.1
  - scipy=1.8.1
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - statsmodels=0.13.2
  - torchvision=0.13.0
  - pip:
    - notexbook-theme==2.0.1